services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:8000"
    volumes:
      - /opt/app/data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "app/manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 5
