# docker-compose.prod.yml
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:8000" 
    volumes:
      - prod_db:/data
      - .:/app 
    entrypoint: ["sh", "/app/entrypoint.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "app/manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  prod_db: {}
