name: Deploy (Prod)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare target dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script_stop: true
          script: |
            set -e
            sudo mkdir -p /opt/myapp
            sudo chown -R $(whoami):$(whoami) /opt/myapp
            ls -ld /opt/myapp || true
            ls -la /opt/myapp | sed -n '1,50p'

      - name: Upload code (exclude junk, keep .env on server)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          source: "./,!./.git/**,!./.github/**,!./.env,!./.env.dev,!./dev_data/**,__pycache__/**,*.pyc"
          target: "/opt/myapp"
          overwrite: true
          rm: false 

      - name: Deploy containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script_stop: true
          script: |
            set -e
            cd /opt/myapp
            docker compose -f docker-compose.prod.yml up -d --build
            docker image prune -f
            docker compose -f docker-compose.prod.yml ps
