name: Deploy (Prod)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          source: "."
          target: "/opt/myapp"
          overwrite: true
          rm: true
          exclude: ".git,.github,.venv,__pycache__,*.pyc,.env,.env.dev,dev_data"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script_stop: true
          script: |
            set -e
            cd /opt/myapp
            docker compose -f docker-compose.prod.yml up -d --build
            docker image prune -f
